/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BubbleChartItem } from "./components/stencil-bubble-chart/bubble-chart-item";
export { BubbleChartItem } from "./components/stencil-bubble-chart/bubble-chart-item";
export namespace Components {
    interface LocalDevComponent {
    }
    interface StencilBubbleChart {
        /**
          * Title (name) of the chart
         */
        "chartTitle": string;
        /**
          * Bubble chart data
         */
        "data": Array<BubbleChartItem>;
    }
}
declare global {
    interface HTMLLocalDevComponentElement extends Components.LocalDevComponent, HTMLStencilElement {
    }
    var HTMLLocalDevComponentElement: {
        prototype: HTMLLocalDevComponentElement;
        new (): HTMLLocalDevComponentElement;
    };
    interface HTMLStencilBubbleChartElement extends Components.StencilBubbleChart, HTMLStencilElement {
    }
    var HTMLStencilBubbleChartElement: {
        prototype: HTMLStencilBubbleChartElement;
        new (): HTMLStencilBubbleChartElement;
    };
    interface HTMLElementTagNameMap {
        "local-dev-component": HTMLLocalDevComponentElement;
        "stencil-bubble-chart": HTMLStencilBubbleChartElement;
    }
}
declare namespace LocalJSX {
    interface LocalDevComponent {
    }
    interface StencilBubbleChart {
        /**
          * Title (name) of the chart
         */
        "chartTitle"?: string;
        /**
          * Bubble chart data
         */
        "data"?: Array<BubbleChartItem>;
    }
    interface IntrinsicElements {
        "local-dev-component": LocalDevComponent;
        "stencil-bubble-chart": StencilBubbleChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "local-dev-component": LocalJSX.LocalDevComponent & JSXBase.HTMLAttributes<HTMLLocalDevComponentElement>;
            "stencil-bubble-chart": LocalJSX.StencilBubbleChart & JSXBase.HTMLAttributes<HTMLStencilBubbleChartElement>;
        }
    }
}
